### ISSUE TITLE
INSTEAD Text-to-Speach function for S60 3rd

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#18]
Спасибо за поддержку сборок для S60 3rd, благодаря чему на Symbian появился интерпретатор языка Lua.
Скажите, а возможно ли добавить в движок INSTEAD функцию воспроизведения строки синтезатором речи смартфона?
Интерпретатор Python для S60, исходники которого также доступны и хорошо документированы, имеет функцию "audio.say" которая позволяет превращать текст в машинный голос.
1) http://www.mobilenin.com/pys60/resources/ex_text_to_speech_1_descr.py
2) https://mail.python.org/pipermail/python-list/2013-March/643049.html
Что скажете, возможно ли научить "разговоривать" INSTEAD?

**Comment by gl00my** [comment]
Сборка для S60 просто поддерживается, но не развивается.Также как и сборка для wince.   У меня больше нет рабочих устройств с этими ОС. 

Что касается голосовых функций для INSTEAD есть как технические вопросы, так и теоретические -- если вы играли в игры то поймете, что озвучка большинства из них мало что даст. Это не cyoa игры, это адвенчуры, где много действий и посещений одних и тех же мест.
