### ISSUE TITLE
ua.ini - Ukrainian language file

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#19]
Here is Ukrainian language file for INSTEAD 2.4.0 (for now INSTEAD use "ua" as Ukrainian identificator, but maybe need use "uk" as it defined by Unicode standart?)

--start--
;$Name:Українська$
UNKNOWN_ERROR = Невідома помилка.
ERROR_MENU = Під час ініціалізації гри виникла помилка:\n\
'%s'\n\
\n\
<a:/select>Так</a>
WARNING_MENU = Під час роботи гри виникла помилка:\n\
'%s'\n\
\n\
<a:/resume>Так</a>
SAVE_SLOT_EMPTY = пусто
SELECT_LOAD_MENU = Завантажте гру\n\n
AUTOSAVE_SLOT = Автозбереження
BROKEN_SLOT = помилка
SELECT_SAVE_MENU  = Збережіть гру\n\n
MAIN_MENU = \
<a:/resume>Продовжити гру</a>\n\
<?:select><a:/select>Вибір гри</a>\n</?>\
<?:themes><a:/themes>Вибір теми</a>\n</?>\
<a:/new>Почати заново</a>\n\
<a:/load_menu>Завантажити гру</a>\n\
<a:/save_menu>Зберегти гру</a>\n\
<a:/about>Інформація</a>\n\
<a:/settings>Налаштування</a>\n\
<a:/ask_quit>Вихід</a>
ABOUT_MENU = \
INSTEAD - %s\n\
\n\
Інтерпретатор простих\n\
текстових пригод:\n\
Косих П.А. '2009-2016\n\
\n\
Адаптація для Windows:\n\
Риндін І.В. '2009\n\
\n\
Сайт проекту:\n\
<u>http://instead.sourceforge.net</u>\n\
\n\
<a:/main>Назад</a>
BACK_MENU = <a:/main>Назад</a>
ON = Так
OFF = Ні
KBD_MODE_LINKS = Посилання
KBD_MODE_SMART = Розумний
KBD_MODE_SCROLL = Прокрутка
FROM_THEME = Тема
SETTINGS_SND_MENU = \
<a:/settings-gfx>[Графіка]</a><w:  ><u>[Звук]</u><w:  ><a:/settings-oth>[Інше]</a>\n\
\n\
Гучність: <a:/vol--><<</a><a:/vol-><</a> <a:/mtoggle>%d%%</a> <a:/vol+>></a><a:/vol++>>></a>\n\
\n\
Якість: <a:/hz-><<</a> %dГц <a:/hz+>>></a>\n\
\n\
Музика: <a:/music>%s</a>\n\
\n\
Звук кліка: <a:/click>%s</a>\n\
\n\
<a:/main>Застосувати</a>
SETTINGS_GFX_MENU = \
<u>[Графіка]</u><w:  ><a:/settings-snd>[Звук]</a><w:  ><a:/settings-oth>[Інше]</a>\n\
\n\
Розмір вікна: <a:/mode--><<</a>%s<a:/mode++>>></a>\n\
Повний екран: <a:/fs>%s</a> / HQ: <a:/hires>%s</a>\n\
Маштаб шрифту: <a:/fs--><<</a>%d%%<a:/fs++>>></a>\n\
Текст по ширині: <a:/just--><<</a>%s<a:/just++>>></a>\n\
Підсвітка посилань: <a:/hl>%s</a>\n\
Ефект переходу: <a:/fading>%s</a>\n\
<?:owntheme>Власні теми гри: <a:/owntheme>%s</a>\n</?>\
\n\
<a:/main>Застосувати</a>
SETTINGS_OTH_MENU = \
<a:/settings-gfx>[Графіка]</a><w:  ><a:/settings-snd>[Звук]</a><w:  ><u>[Інше]</u>\n\
\n\
Режим прокрутки: <a:/motion>%s</a>\n\
Фільтр мишки: <a:/filter>%s</a>\n\
Режим клавіатури: <a:/kbd>%s</a>\n\
\n\
Мова: <a:/lang--><<</a>%s<a:/lang++>>></a>\n\
\n\
Автозберігання: <a:/autosave>%s</a>\n\
\n\
<a:/main>Застосувати</a>
CUSTOM_THEME_MENU = \
Увага!!!\n\
\n\
Гра має власну тему, але підтримка власних тем відключена в налаштуваннях. \
Гра може виглядати не так, як задумував ії автор.\n\
\n\
<i>Ви можете дозволити можливість самовизначення тем в налаштуваннях.</i>\n\
\n\
<a:/resume>Так</a>
OWN_THEME_MENU = \
Увага!!!\n\
\n\
Обрана гра самовизначає тему. Зміни не вступлять в силу.\n\
\n\
<i>Ви можете заборонити можливість самовизначення тем в налаштуваннях.</i>\n\
\n\
<a:/resume>Так</a>
QUIT_MENU = \
Справді вийти?\n\
\n\
<a:/quit>Так</a> | <a:/resume>Ні</a>
SELECT_GAME_MENU = Вибір гри\n\n
SELECT_THEME_MENU = Вибір теми\n\n
SAVED_MENU = \
Гра збережена!\n\
\n\
<a:/resume>Так</a>
NOGAMES_MENU = \
Не знайдено жодної гри.\n\
Будь-ласка, скопіюйте хоча б одну гру в каталог:\n'%s'
NOTHEMES_MENU = \
Не знайдено жодної теми.\n\
Будь-ласка, скопіюйте хоча б одну тему в каталог:\n'%s'\n
CANCEL_MENU = <a:/resume>Відміна</a>
DISABLED_SAVE_MENU = \
Збереження заборонено грою.\n
BROWSE_MENU = \
[...]
REMOVE_MENU = \
Видалити гру?\n\
%s\n\
\n\
<a:/remove>Так</a> | <a:/select>Ні</a>
WAIT_MENU = \
Будь-ласка, зачекайте...
--end--

**Comment by gl00my** [comment]
Is this file fixes original one or you just missed this file in sources?

https://github.com/instead-hub/instead/blob/master/lang/ua.ini

**Comment by Symbian9** [comment]
Symbian installer include only "ru.ini" and "en.ini". 
If some other locales presented in source, it will be better add them to SIS file too.

**Comment by gl00my** [comment]
How to build sources for differnt platforms -- is another question. There are 9 languages and tutorials currently in git, so i am closing this issue.

For .sis we have decided to strip binaries. There are some tricks: converting png to jpg and strip most of languages and tutorials and so on... If you want,  you can build you own variant.

**Comment by Symbian9** [comment]
Also in presented https://github.com/instead-hub/instead/blob/master/lang/ua.ini here is a mistake. Please, correct it:
"Режим миши" -> "Режим миші"
Іn some way, think, better would be "Режим вказівника" (ru"Режим указателя", en"Cursor mode").

**Comment by gl00my** [comment]
btw, 
ua renamed to uk, thank you

**Comment by gl00my** [comment]
Ok, will fil translation

**Comment by gl00my** [comment]
Не могу найти фразу: "Режим миши" 
Лучше патч

**Comment by Symbian9** [comment]
Извините, сначала не то написал, вот то что нужно исправить:

Фільтр миши: <a:/filter>%s</a>\n\

Замените на:

Фільтр миші: <a:/filter>%s</a>\n\

Хотя, как мне кажется, вообще лучше вместо "мышь" использовать термин ru"указатель"(uk"вказівник", en"cursor").

P.S.: Патчи делать пока не умею...

**Comment by gl00my** [comment]
Ок, исправлю.

**Comment by Symbian9** [comment]
Вот ещё нашел одну ошибку:
SELECT_SAVE_MENU = Збережить гру\n\n 

Замените на:

SELECT_SAVE_MENU = Збережіть гру\n\n 

Спасибо за оперативность!

**Comment by gl00my** [comment]
А точно? Я не знаю украинского, но вот уже третий украинец исправляет этот файл, и у меня честно говоря уже возникают вопросы. :)

**Comment by gl00my** [comment]
Власні теми гри: %s -- разве это не означает Собственная тема ИГРЫ? Должно быть ИГР?
В общем, мне нужно подтверждение какое-то, чтобы я был уверен в правильности правок.

**Comment by Symbian9** [comment]
http://chak-chy-pravylno-my-hovorymo.wikidot.com/gh
"Особливості відмінювання полягають у тому, що в однині у відповідній відмінковій формі виступає слово гра (без і), а в усіх відмінках множини на початку додається і (ігри)."
Тоесть, в зависимости от того какое число, множественное или единичное, употребляется: если настройки одной или конкретной игры то "Власна тема гри", если настройки множества игор тогда "Власні теми ігор". В случае у правильней будет на русском "Собственная тема игры" потому как в один момент пользователя играет только одну игру, а в украинском переводе будет "Власна тема гри".

Родительный падеж слова ru"игра":
- одной -- uk"гри"
- множества -- uk"ігор".

uk"ігр" - это неправильное слово!

**Comment by gl00my** [comment]
Исправил

**Comment by Symbian9** [comment]
Также нужно будет исправить строки перевода во всех остальных файлах где использовался тег "ua" на соответствующий "uk" (в играх, темах и документации)

**Comment by gl00my** [comment]
ok, сделал

**Comment by Symbian9** [comment]
Не совсем, ещё во всех темах нужно будет поправить, к примеру вот в стандартной и сейчас "uа"
https://github.com/instead-hub/instead/blob/master/themes/default/theme.ini

**Comment by gl00my** [comment]
fixed

**Comment by Symbian9** [comment]
Нашел ещё одну ошибку в украинской локали, посередине слова вставлена прописная буква "І". 
Замените слово "ІнформацІя" на "Інформація"

P.S. Надеюсь, это уже последняя ошибка.

**Comment by gl00my** [comment]
fixed
