### ISSUE TITLE
Support SVG graphics

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#20]
En: Add possibillity to use SVG graphics to INSTEAD game or theme.
Ru: Добавьте возможность использования SVG для оформления игры или темы в INSTEAD.
1) http://www.linuxmotors.com/SDL_svg/
2) http://www.gamedev.net/topic/652219-resolution-independent-graphics-with-svg-in-sdl/
3) http://forums.libsdl.org/viewtopic.php?t=8911&sid=44ead779d4e465a34c71df70333ce704
4) http://www.gamedev.ru/code/forum/?id=203028
5) https://mail.gnome.org/archives/libart/2001-April/msg00002.html

**Comment by gl00my** [comment]
1. The code must be compiled with SDL1 and SDL2 (its like, that SDL_svg builds with SDL1 only).
2. libsvg is another dependence, SDL_gfx is another dependence
3. INSTEAD must be simple enoth to be highly portable
4. INSTEAD currently is raster oriented, all sizes are in pixels
5. there are a lot of formats to do: apng, webm and other...

So, i suppose, INSTEAD must stay simple. Currently this issue moved to 'wont fix status', sorry.
