### ISSUE TITLE
Few icons missed in INSTEAD-2.4.0.sis

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#21]
B сборке INSTEAD 2.4.0 для Symbian отсутствуют следующие иконки флагов, используемые в обучающей игре поставляемой с интерпретатором: 
1) https://github.com/instead-hub/instead/tree/master/games/tutorial3/de.png
2) https://github.com/instead-hub/instead/tree/master/games/tutorial3/fr.png

**Comment by gl00my** [comment]
Thank you! Fixed

**Comment by Symbian9** [comment]
Пожалуйста, проверьте ещё наличе в SIS следующих файлов:
2) https://github.com/instead-hub/instead/tree/master/games/tutorial3/main-de.lua
3) https://github.com/instead-hub/instead/tree/master/games/tutorial3/main-fr.lua

**Comment by gl00my** [comment]
fixed
