### ISSUE TITLE
On Symbian Ogg files can play only 1 second

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#22]
Сейчас в версии для S60 3rd (NokiaN82) звуки в формате Ogg проигрываются только одну секунду после загрузки страницы на которой должен играть этот файл.
В то же время остальные звуки в форматах MOD и XM воспроизводятся нормально. 
Может есть способ как это исправить?
1) http://wiki.scummvm.org/index.php/Compiling_ScummVM/Symbian
2) https://github.com/scummvm/scummvm/tree/master/backends/platform/symbian/
3) http://forums.libsdl.org/viewtopic.php?t=8569
4) https://sourceforge.net/projects/s60oggvorbiscodec/
5) http://anotherguest.se/ (смотрите в самом низу есть разные сборки SDL_mixer'а)

В порте ScummVM для S60v3 заявлена поддержка Ogg: 
http://forums.scummvm.org/viewtopic.php?t=6209
(я проверял изменение громкости на INSTEAD и это не исправило данную проблему, и Ogg все равно проигрывается только одну секунду)

Есть ещё вот такой кодек Ogg на C (лицензию publicdomain)
http://nothings.org/stb_vorbis/

**Comment by gl00my** [comment]
Я не смог победить эту проблему. Насколько я помню -- некоторые файлы все-таки игрались. В любом случае, развитие порта для S60 находится только в режиме поддержки. Если кто то сможет решить проблему и пришлет решение - я включу его,

**Comment by Symbian9** [comment]
А есть ли у Вас мелодия "instead.ogg", поставляемая с обучающей игрой, в другом формате? Скажем, в MOD или XM?
Модули ведь INSTEAD играет отлично на всех платформах, ну и размер модулей всегда меньше результирующего Ogg файла.

**Comment by gl00my** [comment]
Нет, это оригинальная композиция написанная для instead. Менять трек -- есть ли в этом смысл? Это всего лишь обучение, в играх в любом случае будут треки в ogg и возможно даже mp3. Так что придется воспринимать все это пока как ограничения в s60 версии...

**Comment by gl00my** [comment]
p.s. я добавил все языки в s60 версию

**Comment by gl00my** [comment]
wontfix
