### ISSUE TITLE
LuaJIT implementation for INSTEAD

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#23]
Есть ли смысл включить LuaJIT в код движка INSTEAD? В теории, это должно улучшить в первую очередь производительность на устройствах с маломощными процессорами:
http://luajit.org/performance_arm.html

**Comment by gl00my** [comment]
нет. instead и так может собираться с lua5.1/5.2/5.3 и luajit, зачем вклбчать его в исходный код?
