### ISSUE TITLE
Data path correction for Symbian

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#24]
В связи со спецификой платформы S60, в любой папке которая содержит изображения автоматически создается вложенная папка с именем "_PAlbTN", содержащая несколько превью для каждого изображения в данной папке. По сути идет многоразовая перезапись носителя и насыщение файловой структуры. 
1) http://www.howtoquick.net/2012/11/palbtn-folder-in-nokia-phone-memory-card-how-to-remove.html
2) http://forums.techarena.in/portable-devices/1402360.htm
3) http://forum.smart60.ru/index.php?showtopic=14682
4) http://dimonvideo.ru/articles/1888
В случае с INSTEAD в каждой папке данных игры или темы по пути "E:\Data\instead.."(или же "C:\Data\instead..") содержащей картинки происходит тоже самое.
Для решения данной проблемы предлагаю применить способ использованый в программе "ViewRanger", в которой скачиваемые файлы помещаются сразу в папки вложенные внутрь "E:ViewRanger\MapCache_PAlbTN..", тем самым препятствуя системе создавать дополнительные вложенные папки с именем "_PAlbTN" 
5) http://www.sasgis.org/mantis/file_download.php?file_id=1955&type=bug
Тоесть, предлагаю для избежания создания кучи ненужных папок и файлов внести изменения в правилах компиляции INSTEAD для S60v3 заменить путь к данным интерпретатора:

" ! : \ Data \ instead \ .." 

На этот путь:

"! : \ Data \ instead \ _PAlbTN \ .."

**Comment by gl00my** [comment]
не готов вносить такие глубокие изменения вслепую. как я говорил, с моей стороны развитие версии для s60 заморожено. если вы хотите помочь проекту на s60, научитесь собирать проект и высылайте отлаженные проверенные патчи.

**Comment by gl00my** [comment]
wontfix
