### ISSUE TITLE
Incorrect symbols in PDF documentation (generated from developers WIKI)

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#25]
Примеры кода в PDF документации содержат некорректные символы. 
Вот например вместо символа ' (U+0027) подставляется (U+2019), а вместо " (U+0022) подставляется символ (U+201D).
Заметил это при попытках скопировать-вставить пример кода из PDF в main.lua

**Comment by gl00my** [comment]
Я не нашел рабочего решения проблемы. Думаю, это не единственная конвертация, в любом случае -- основное назначение pdf -- читать и печатать.  Если кто то сможет решить проблему - приму патч.
