### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [instead-hub/instead#26]
Please, add a button "Get it on F-Droid" with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg in your README file and website with the appropriate link to the page of your app on F-Droid.

**Comment by gl00my** [comment]
I am sorry, but we are no support this build. We have no contact with it's author.
We have this one: https://github.com/instead-hub/instead-android-ng
I hope it is much better, but it is not currently in f-droid repo;
