### ISSUE TITLE
Update links in F-Droid

### ISSUE THREAD

**Issue by PanderMusubi** [instead-hub/instead#27]
Please update the links in https://f-droid.org/repository/browse/?fdfilter=instead&fdid=com.silentlexx.instead for issues and source code to GitHub.

**Comment by gl00my** [comment]
I am sorry, but we are no support this build. We have no contact with it's author.
We have this one: https://github.com/instead-hub/instead-android-ng
I hope it is much better, but it is not currently in f-droid repo;

**Comment by PanderMusubi** [comment]
OK, you can ask for an update of the URLs in F-Droid from which it builds via https://gitlab.com/fdroid/fdroiddata/issues
