### ISSUE TITLE
Default portrait theme

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#32]
I propose add "Standart (portrait)" theme.

Here is code for "theme.ini":
```
; $Name: Standart (portrait)$

scr.w = 600
scr.h = 800
scr.gfx.bg = bg-portrait.png

win.align = justify
win.x = 48
win.y = 8
win.w = 500
win.h = 568

win.scroll.mode = 2
win.ways.mode = top

inv.x = 8
inv.y = 620
inv.w = 564
inv.h = 144

inv.mode = horizontal-left

menu.button.x = 576
menu.button.y = 776
```

For "bg-portrait.png" propose use background image from original "Standart" theme, only need rotate it on 90 degrees clockwise
* https://github.com/instead-hub/instead/blob/master/themes/default/bg.png

Thats all.

**Comment by gl00my** [comment]
wontfix
