### ISSUE TITLE
INSTEAD 2.5.0 crashed on S60v3

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#33]
INSTEAD 2.5.0 dropdown immediatly after try run it on Symbian 9.2 (S60v3)

Here is content of <code>C:\Data\instead\stderr.txt</code> log:
```
Using data from: E:\data\instead
No games found in: ./games/.
Error: cannot open ./stead//stead.lua: No such file or directory
Error: cannot open ./stead//stead.lua: No such file or directory
Fatal error! Can't init anything!!!
```

Look like something wrong with data path.

Used SIS (installed OK):
* http://instead.syscall.ru/instead/2.5.0/instead-2.5.0.sis

**Comment by gl00my** [comment]
Its like that c code was not recompiled. Will try check it later today.

**Comment by gl00my** [comment]
I have compiled s60 port. Please, try it and write if it works/not works.
Url is same: http://instead.syscall.ru/instead/2.5.0/instead-2.5.0.sis

**Comment by Symbian9** [comment]
Now I can install & run it, but <code>C:\Data\instead\stderr.txt</code> log include next:
```
Using data from: E:\data\instead
No games found in: ./games/.
Video mode: 320x240@16bpp
Can't load: nl.png
```

**Comment by gl00my** [comment]
"No games found in: ./games/" message is fine. It is standard path, but there is also appdata/games and it must works.
I have reuploaded sis with nl.png (i hope)

**Comment by Symbian9** [comment]
I reinstall latest build now.

Well, now I also hope that all will work fine.

**Comment by Symbian9** [comment]
I try set 240*320 mode from "Settings" dialog, but its not work (only 320*240 work).

Also look like there are still some mistakes in path definition (double slash in theme sound path) 
```
Using data from: E:\data\instead
No games found in: ./games/.
Video mode: 320x240@16bpp
Unable to set 240x320 video: Requested video mode is not supported
Video mode: 320x240@16bpp
Can't load: E:/data/instead/themes/default//click.wav
 ```

**Comment by gl00my** [comment]
Ok, will upload nl. But can you run games? Are they working?

Support of modes is sdl problem i will not fix it. The port is supported only in compilation mode. :)

// is normal, but can it be problem in s60? In fact, its like that click.wav is just cant be loaded. All pathes in themes hav //

**Comment by gl00my** [comment]
No response, so close
