### ISSUE TITLE
Manuals punctuation mistakes (wiki, tex, PDF)

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#34]
I try read & check all documents from <code>/doc/..</code> folder from this archive:
* http://instead.syscall.ru/instead/2.5.0/instead_2.5.0.tar.gz

And find many mistakes in punctuation (mostly incorrect symbols), so propose check it & replace next symbols (especially in code blocks):
* ‘ u+2018 --> ' u+0027
* ’ u+2019 --> ' u+0027
* “ u+201C --> " u+0022
* ” u+201D --> " u+0022

Also here is mistake with comma:
* {sans„sans-i} u+201E --> {sans,sans-i} u+002C

**Comment by gl00my** [comment]
I have add uquote package in tex template for stead3 manual. Hope it will help.
Anyway, if you want copy & paste, do it with stead3.md file. pdf files are for printing.
{sans„sans-i} u+201E --> {sans,sans-i} u+002C 
It is not the bug, please, read manual.

**Comment by Symbian9** [comment]
> {sans„sans-i} u+201E --> {sans,sans-i} u+002C
It is not the bug, please, read manual

Well, I read <code>stead3.pdf</code> again, and still can't find why here used "U+201E DOUBLE LOW-9 QUOTATION MARK"? Its only one <code>„</code> symbol in this PDF document, without description about this special symbol.

**Comment by gl00my** [comment]
I did not rebuild pdf. It will happen on next prerelease (beta). You can try make it yourself. You need: multimarkdown and xetex. See Makefile in doc

**Comment by Symbian9** [comment]
Короче, еще раз "на русском": внутри текста <code>/doc/stead3.md</code> содержится опечатка - две запятых вместо одной:
> ... Вы можете опускать какие-то начертания, и сам сгенерирует их на основе обычного начертания, например {sans,,sans-i}.ttf (заданы только regular и italic);

Смотри Markdown-версию:
* https://github.com/instead-hub/instead/blob/master/doc/stead3.md

В результате, во время конвертации в PDF две запятых подряд <code>,,</code> (U+002C COMMA) конвертируются в <code>„</code> (U+201E DOUBLE LOW-9 QUOTATION MARK).

Все описанные выше ошибки/опечатки также присутствуют и в документации к STEAD2.

**Comment by gl00my** [comment]
Это не ошибки. Две запятых превратились в символ - две запятых. И аналогично с кавычками. Pdf это для печати. А не для копи пасты или анализа кода символов. Тем не менее, я внес в tex шаблон модуль, который скорее всего "исправит" кодовые вставки. Но pdf и тарболл я не буду перезаливать до следующего релиза. Пока же, для копи пасты, используй .md файл. Или собери pdf сам. Но повторюсь, это не ошибка.

**Comment by gl00my** [comment]
Еще раз, на всякий случай, две запятых подряд в md файле это тоже не ошибка. Почему? Потому что опущено начертание bold. Прочти документацию.

**Comment by Symbian9** [comment]
Да я не о том, как "две запятых превратились в символ - две запятых", а том зачем вообще там использовать две запятых?

В чем необходимость в данном конкретном примере кода использовать две запятых?
> {sans,,sans-i}.ttf

Почему не использовать просто с одной запятой?
> {sans,sans-i}.ttf

**Comment by gl00my** [comment]
Пргчитай внимательно сообщение выше. Потом документацию. Как еще объяснить что там две запятых это не ошибка - я не знаю. :)

**Comment by gl00my** [comment]
Ну попробую еще раз. Если будет одна запятая, то для болд начертания будет использоваться италик. А мы хотим, чтобы болд начертание сгенерировалось движком. Прочитай пожалуйста документауию.

**Comment by Symbian9** [comment]
Во всей документации только один подобный пример, и нигде больше две запятых подряд в документации не используются.

Зачем усложнять движок? Почему не сделать так, что если движок не находит какого-то начертания в фигурных скобках {...}, то движок сразу же сам опознает что опущено.

Чтобы достаточно было написать {sans,sans-b}.ttf с одной запятой, и движок сразу же понял, что нехватает sans-i.

**Comment by gl00my** [comment]
Без чтения документации разговор бессмысленный. Извини. Закрываем тему

**Comment by Symbian9** [comment]
лучше тогда уж такой синтаксис для автогенерации
<code>{sans,sans-b,~}.ttf</code>
