### ISSUE TITLE
INSTEAD updated on PPA for Ubuntu

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#41]
On `ppa:instead/ppa` already exist v3.1.2
* https://launchpad.net/~instead/+archive/ubuntu/ppa

But in "Download" section on official site it still shown as v3.0.0

> Ubuntu packages 3.0.0
> 
> http://instead.syscall.ru/download/

### REFERENCE
* http://instead.syscall.ru/2017/08/30/debian-3-1-2/

**Comment by gl00my** [comment]
fixed
