### ISSUE TITLE
Keep Symbian 9.x in supported platforms!

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#42]
> https://instead.syscall.ru/talk/index.php/563-instead

Please, don't drop support for S60v3, S60v5, S^1, S^3 devices!

P.S.: We are still alive! ;-)
- https://github.com/mrRosset/Symbian-Archive
- https://github.com/search?o=desc&q=s60&s=updated&type=Repositories&utf8=%E2%9C%93

**Comment by gl00my** [comment]
ok! got it
