### ISSUE TITLE
sprite.copy в stead2

### ISSUE THREAD

**Issue by spline1986** [instead-hub/instead#43]
![screen_instead3 2_satori](https://user-images.githubusercontent.com/6873929/35720029-d57d8aa0-080d-11e8-9f04-7dbdb8e5f1db.png)

В версии из мастера и более ранних сборках (последняя сборка под андроид) почему-то не работает прозрачность в Сатори. Насколько я понимаю, проблемы возникают с sprite.copy с указанием значения альфа-канала.

**Comment by gl00my** [comment]
А что должно быть? Поясни, а то я не помню абсолютно. Что ожидается на экране?

**Comment by spline1986** [comment]
Думается мне, что это стоит считать багом в игре. Использование copy вместо draw для вывода изображения с альфа-каналом, ЕМНИП, и в документации описано.

**Comment by spline1986** [comment]
@gl00my надпись и прогресс-бар внизу имеют альфа-канал. Но при sprite.copy() альфа-канал теперь не учитываются. Поэтому надпись абсолютно непрозрачна.

**Comment by gl00my** [comment]
Ага, поизучаю, спасибо!

**Comment by spline1986** [comment]
Ага. Заработало. Спасибо за фикс =)

**Comment by gl00my** [comment]
Действительно, в документации по stead2 (и даже stead3) copy и compose может вызываться с alpha!
Так как сейчас draw с alpha ускорено за счет SDL2 я сделал так:
1) поведение stead2 эмулируетсяв lua слое
2) поведение stead3 изменено. copy и compose больше не работают с alpha. 
Документацию изменил.
