### ISSUE TITLE
Add latest "stead3.pdf" as asset to each INSTEAD3 release

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#49]
Current PDF look bad...

![stead3.pdf](http://i.imgur.com/sy09Igr.png)

### TODO

- Remove "executable" property from this PDF before upload it as asset:
  - [ ] `$ chmod a-x stead3.pdf`
- Add latest "Documentation (pdf)" as asset to each release:
  - [ ] `https://github.com/instead-hub/instead/releases/download/3.x.x/stead3.pdf`

**Comment by gl00my** [comment]
-rw-r--r--  1 peter peter  94288 Apr 22 14:37 modules3.pdf
-rw-r--r--  1 peter peter 316447 Apr 22 14:37 stead3.pdf


So, the problem is on your side?

**Comment by Symbian9** [comment]
> So, the problem is on your side?

Hm, maybe.

**Comment by Symbian9** [comment]
> modules3.pdf

@gl00my, please, add `modules3.pdf` to releases assets too.
