### ISSUE TITLE
Rename Russian docs "stead3.md" &"modules3.md" to  "stead3-ru.md" & "modules3-ru.md"

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#52]
Original in Russian:

- https://github.com/instead-hub/instead/blob/master/doc/stead3.md
- https://github.com/instead-hub/instead/blob/master/doc/modules3.md

### TODO

- [ ] https://github.com/instead-hub/instead/blob/master/doc/stead3-ru.md
- [ ] https://github.com/instead-hub/instead/blob/master/doc/modules3-ru.md

**Comment by gl00my** [comment]
fixed.

**Comment by gl00my** [comment]
renamed..
