### ISSUE TITLE
"instead-doc-en" & "instead-doc-ru" dropped? (packaging)

### ISSUE THREAD

**Issue by Symbian9** [instead-hub/instead#53]
From topic about packaging INSTEAD 3.2.0/3.2.1 for MX Linux (Debian "Stretch")

> - https://forum.mxlinux.org/viewtopic.php?f=55&t=44919&p=444497&#p444497
> 
> OK...3.2.1 drops the English and Russian documentation for some reason, so I'm cutting out those packages.

**Comment by gl00my** [comment]
it was old stead2 documentation. it is not actual anymore.
