### ISSUE TITLE
Two typos at english web page?

### ISSUE THREAD

**Issue by Randrianasulu** [instead-hub/instead#58]
> https://instead-hub.github.io/en/

it says:

>   About
> INSTEAD was designed to make the textographic games.
> This games are mix of interactive ficrtion, visual novels and classic point & click adventures.
----------------
I think this sentecnce must be written like this:
**These** games are mix of interactive **fiction**, visual novels and classic point & click adventures.

**Comment by alex-0xFF** [comment]
Yep, it's definitely the typos.

**Comment by gl00my** [comment]
fixed, thank you
