### ISSUE TITLE
OS Keyboard layout is not honored

### ISSUE THREAD

**Issue by watttman** [instead-hub/instead#63]
The games do not honor the OS keyboard layout (I use bulgarian-bds cyrillic layout).
So when I type "да" it shows up as "щв".
This renders the game unplayable for anyone who uses a keyboard layout other than the one hardcoded in the engine

**Comment by gl00my** [comment]
This is architecture problem. instead handles keys by scancodes. not symbols.
So, you must add own layout in lua. What game are you trying?

**Comment by gl00my** [comment]
Some metaparser3 games can be played with chat-bots (telegram for example) with native input.

**Comment by gl00my** [comment]
I will try fix it in future versions... Thank you for bugreport. :)

**Comment by watttman** [comment]
I tried few games of the last ones from here http://instead-games.ru/ (Метель, Другой Марс etc)
Only the ones which suggest words are playable via the mouse.
Thanks for considering a fix:)

**Comment by gl00my** [comment]
Ок, i hope the next version will support i18n input.. and the parser module
will be updated

пт, 1 мар. 2019 г., 23:56 watttman <notifications@github.com>:

**Comment by gl00my** [comment]
Ok. instead 3.3.0 is out with unicode input support. metaparser3 module was updated too.
Currently there are only two games, that uses this new input methods:

http://instead-games.ru/game.php?ID=320
http://instead-games.ru/game.php?ID=298

You can try it online. In few days Android port of instead will be updated soon.
Windows version of those games: https://instead.itch.io

But in future there will be a lot.
