### ISSUE TITLE
Дополните руководство

### ISSUE THREAD

**Issue by luckyuk** [instead-hub/instead#69]
Пожалуйста дополните руководство разделом, где перечислены обработчики объектов, как это сделано для [методов объектов](https://github.com/instead-hub/instead/blob/master/doc/stead3-ru.md#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2).

**Comment by gl00my** [comment]
https://github.com/instead-hub/instead/blob/master/doc/stead3-ru.md#%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%B0%D1%82%D1%80%D0%B8%D0%B1%D1%83%D1%82%D0%BE%D0%B2-%D0%B8-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2
