### ISSUE TITLE
Consider adding support for right-to-left text

### ISSUE THREAD

**Issue by mehdisadeghi** [instead-hub/instead#76]
While translating "The Returning of the Quantum Cat", I noticed the engine can not render right-to-left text. so I open this issue to track this new feature which I'm working on it.

There are multiple things that should be fixed:

- [ ] SDL_ttf should be compiled with HarfBuzz support (there is a flag for it `TTF_USE_HARFBUZZ`)
- [x] Word coordinates should be calculated based on logical rather than physical `x` position
- [x] Simultanious LTR and RTL rendering is necessary if there are mixed content
- [ ] UI should be translated (for the menus)
- [x] A theme with a font such as DejaVuSans that contains all the necessary glyphs.

I have already made most of these changes on my fork (not published yet) and can successfully render and play The Returning of the Quantum Cat (my favorite game!).

Any feedback is appreciated. 

Edit: you can assign this to me.

Edit 2: Here is a picture of the game in Persian.
![image_2020-08-07_17-11-27](https://user-images.githubusercontent.com/3101557/89707728-2300ac80-d971-11ea-9334-4de9f237d1f8.png)

**Comment by gl00my** [comment]
That's cool. Waiting pull requests =)

**Comment by mehdisadeghi** [comment]
I have almost completed adding multilingual text rendering support to Instead. Below is a sample picture. There are still minor bugs here and there, but it works good enough. I'll submit another PR.

![good_sample_alphanumeric](https://user-images.githubusercontent.com/3101557/91490299-84ea6d00-e8b2-11ea-9e05-ae7304f4f2ba.png)

**Comment by gl00my** [comment]
Good news! :)

чт, 27 авг. 2020 г., 23:14 Mehdi Sadeghi <notifications@github.com>:

**Comment by mehdisadeghi** [comment]
Since the RTL support is in master, I'll close this.
