### ISSUE TITLE
Lua is not sandboxed

### ISSUE THREAD

**Issue by link2xt** [instead-hub/instead#86]
A simple example which demonstrates that games have full access to the filesystem:
```
function init()
        local file = io.open("foobar.txt", "w")
        io.output(file)
        io.write("foobar\n")
        io.close(file)
end
```

Is it expected that games should be trusted and have full access to user files, network etc.?

**Comment by gl00my** [comment]
Lua is sandboxed. Access is granted only in the game and save dir. Module loading is disabled by default. -standalone parameter disables sandbox.

https://github.com/instead-hub/instead/blob/master/stead/stead3/ext/sandbox.lua

**Comment by link2xt** [comment]
Looks good, actually, I did not notice this sandbox. It's still not a whitelist, though.

http://lua-users.org/wiki/SandBoxes suggests creating a new environment with only safe functions there, rather than overwriting all unsafe functions you know about (and potentially missing some of them).

**Comment by gl00my** [comment]
I know that method and use it in my work, but INSTEAD uses this one, and i do not want to break compatibility with tons of games.

**Comment by link2xt** [comment]
Ok, the sandbox is here and I don't see any obvious way to break out of it, closing the issue.
