### ISSUE TITLE
site `http://instead.hugeping.ru/` is not secure

### ISSUE THREAD

**Issue by chenrui333** [instead-hub/instead#92]
👋  just heads up, it looks like the site is not secure (not sure if it is the cert expiration thing or not).

relates to Homebrew/homebrew-core#79839

**Comment by gl00my** [comment]
Can you please explain what you means?
1. Site is read only static generated with hugo.
2. It supports https via github pages

So, i really cant understand whats the problem?

**Comment by gl00my** [comment]
Hah, i see. Somewone pr http->https :)
So, it is not security issue.

**Comment by carlocab** [comment]
Your site seems to have an expired certificate:
```
❯ curl -LI https://instead.syscall.ru/
curl: (60) SSL: no alternative certificate subject name matches target host name 'instead.syscall.ru'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by gl00my** [comment]
instead.syscall.ru is not mine anymore. 
Please, use instead.hugeping.ru
Or just https://instead-hub.github.io

**Comment by carlocab** [comment]
I see. Thanks!

**Comment by chenrui333** [comment]
> Please, use instead.hugeping.ru

cool, I will use that, thanks!
