### ISSUE TITLE
[Feature Request] Consider adding Minetest support

### ISSUE THREAD

**Issue by GrimPixel** [instead-hub/instead#93]
Minetest is a voxel game like Minecraft, but it's free and open-source:
https://www.minetest.net/

Its mods are in Lua, which is also used in INSTEAD. So I guess some people may be able to do this.

**Comment by gl00my** [comment]
Its not goal of the instead project. So, address this issue to minetest if you want.

**Comment by GrimPixel** [comment]
OK, thanks.
